apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mulib-local
  annotations:
    description: 'Local development wadm file for mulib'
spec:
  components:
  # component
    - name: composer
      type: component
      properties:
        # image: ghcr.io/wasmcloud/components/http-hello-world-rust:0.1.0
        image: file://../component/composer/build/composer_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 10
        - type: link
          properties:
            target: keyvalue
            namespace: wasi
            package: keyvalue
            interfaces: [store]
            target_config:
              - name: keyvalue-url
                properties:
                  url: redis://127.0.0.1:6379

  # capabilities
    - name: keyvalue
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-redis:0.25.0

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:52d425d100284eeb29e79ba9fbd5a70f8fbd2a41
        config:
          - name: bind-addr
            properties:
              routing_mode: path
              default_address: 0.0.0.0:8080
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: composer
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: comp-path
                  properties:
                    path: /composer